---
version: '3.8'

services:
  tor:
    build:
      context: ../tor
      dockerfile: Dockerfile
    volumes:
      - ./data/tor/hidden_service:/var/lib/tor/hidden_service:rw
      - ../tor/config:/etc/tor:ro
    restart: unless-stopped
    networks:
      - onion_network
    depends_on:
      - webapp
    user: root

  webapp:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app:ro
    networks:
      - onion_network
    restart: unless-stopped
    # Port exposure is optional since Tor will access it 
    # through the internal network
    # ports:
    #   - "5000:80"

networks:
  onion_network:
    driver: bridge 