version: '3.8'

services:
  tor:
    build:
      context: ../tor
      dockerfile: Dockerfile
    volumes:
      - ./data/tor/hidden_service:/var/lib/tor/hidden_service
      - ../tor/config:/etc/tor
    environment:
      - TOR_THREADS=4
      - HIDDEN_SERVICE_PORT=80
      - SECURITY_LEVEL=high
    restart: unless-stopped
    networks:
      - onion_network
    depends_on:
      - webapp
    user: root

  # webapp:
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./app:/app
  #   networks:
  #     - onion_network
  #   restart: unless-stopped
  # Port exposure is optional since Tor will access it through the internal network
  # ports:
  #   - "5000:80"

  # Example Redis service (uncomment if needed)
  # redis:
  #   image: redis:alpine
  #   networks:
  #     - onion_network
  #   restart: unless-stopped

  # Example load balancer (uncomment if needed)
  # loadbalancer:
  #   image: nginx:alpine
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   networks:
  #     - onion_network
  #   depends_on:
  #     - webapp
  #   restart: unless-stopped

networks:
  onion_network:
    driver: bridge 