services:
  tor:
    build:
      context: ./tor
      dockerfile: Dockerfile
    volumes:
      - ./data/tor/hidden_service:/var/lib/tor/hidden_service:rw
      - ./tor/config:/etc/tor:ro
    restart: unless-stopped
    networks:
      - onion_network

  # Example Redis service (uncomment if needed)
  # redis:
  #   image: redis:alpine
  #   networks:
  #     - onion_network
  #   restart: unless-stopped

  # Example load balancer (uncomment if needed)
  # loadbalancer:
  #   image: nginx:alpine
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   networks:
  #     - onion_network
  #   depends_on:
  #     - webapp
  #   restart: unless-stopped

networks:
  onion_network:
    driver: bridge 