name: Update Docker Hub Description

on:
  push:
    branches: [ "master", "main" ]
    paths:
      - 'README.md'

jobs:
  update-dockerhub-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Process README for Docker Hub
        id: process-readme
        run: |
          # Create processed README
          cat README.md > processed-readme.md
          
          # Replace ASCII art with simpler version (replace first code block)
          awk '
            BEGIN {first=0; printed=0}
            /^```$/ {
              if (first == 0) {
                first = 1;
                print "```";
                print ".d88b.       w             888b.            8    ";
                print "8P  Y8 8d8b. w .d8b. 8d8b. 8   8 .d8b. .d8b 8.dP ";
                print "8b  d8 8P Y8 8 8\047 .8 8P Y8 8   8 8\047 .8 8    88b  ";
                print "`Y88P\047 8   8 8 `Y8P\047 8   8 888P\047 `Y8P\047 `Y8P 8 Yb";
                print "```";
                next;
              }
              if (first == 1 && printed == 0) {
                printed = 1;
                next;
              }
            }
            (first == 0 || printed == 1) {print}
          ' processed-readme.md > temp-readme.md && mv temp-readme.md processed-readme.md
          
          # Remove Table of Contents up to but not including Overview
          sed -i '/^## Table of Contents/,/^## Overview/{/^## Overview/!d}' processed-readme.md
          
      - name: Update Docker Hub Description directly
        run: |
          # Get a token
          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST \
            -d '{"username": "tn3w", "password": "${{ secrets.DOCKER_HUB_TOKEN }}"}' \
            https://hub.docker.com/v2/users/login/ | jq -r .token)
          
          # Update the description
          DESCRIPTION=$(cat processed-readme.md)
          
          # Create JSON payload
          echo '{
            "full_description": '"$(jq -Rs . <<< "$DESCRIPTION")"'
          }' > payload.json
          
          # Send PATCH request
          curl -s -X PATCH \
            -H "Content-Type: application/json" \
            -H "Authorization: JWT ${TOKEN}" \
            -d @payload.json \
            https://hub.docker.com/v2/repositories/tn3w/oniondock/ 